name: genius_lyrics
description: Dart native package inspired by LyricsGenius Python library.  genius_lyrics provides a simple interface to the song, artist, and lyrics data stored on Genius.com.
version: 1.0.1
homepage: https://github.com/hbtalha/genius_lyrics

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  beautiful_soup_dart: ^0.3.0
  http: ^1.1.0
  universal_io: ^2.2.2

dev_dependencies:
  test: ^1.24.3
  flutter_lints: ^2.0.0
